root_dir: ../../data/benchmark/bandgap
id_prop: benchmark
target: bandgap
log_dir: ./logs/bandgap

# root_dir: ../../data/benchmark/coremof
# id_prop: benchmark
# target: N2-77-100000
# log_dir: ./logs/coremof

# root_dir: ../../data/benchmark/ch4n2
# id_prop: benchmark
# target: ch4n2ratio-1bar
# log_dir: ./logs/ch4n2

# root_dir: ../../data/benchmark/tsd
# id_prop: benchmark
# target: tsd
# log_dir: ./logs/tsd

# root_dir: ../../data/benchmark/hmof
# id_prop: benchmark
# target: CO2-298-2.5
# log_dir: ./logs/hmof

epochs: 120
batch_size: 64
early_stopping: 20
