root_dir: ../../data/benchmark/bandgap
id_prop: benchmark
target: bandgap
ckpt: scratch
log_dir: "./logs/bandgap"
devices: [2]

# root_dir: ../../data/benchmark/coremof
# id_prop: benchmark.csv
# target: N2-77-100000
# ckpt: scratch
# log_dir: "./lightning_logs/coremof"
# devices: [0, 1, 2, 3]

epochs: 300
batch_size: 64
early_stopping: 20
kfold: 5
