ckpt: ./lightning_logs/mechan/useStructFeat/pretrain/all/N2-77-100000/version_0/checkpoints/last.ckpt # e.g. ./lightning_logs/version_0/checkpoints/last.ckpt

feat:
  save:
    - cls
    # - tc
    # - vf
    - structure
    # - potential
    # - attn # include self attn and cross attn
  attn:
    sample: true
    sample_num_per_batch: 5
  structure:
    feat: false
    attn: true
    atom_num: true
    sample: false
    sample_num_per_crystal: 20
  potential:
    feat: false
    attn: true
    sample: false
    sample_num_per_crystal: 20
    value: true
    agc: true

# coremof
batch_size: 128
root_dir: ./data/benchmark/coremof
modal_folder: "."
id_prop: benchmark.train
log_dir: ./lightning_logs/feat
save_dir: ./vis/feat
device: [0]
