# configable
epochs: 60
ckpt: ./lightning_logs/tmp/CH4-298-2.5/version_0/checkpoints/epoch=0-step=79.ckpt

# hmof
root_dir: ./data/benchmark/hmof
modal_folder: "."
id_prop: benchmark.val
log_dir: ./lightning_logs/tmp/predict
device: [0]

batch_size: 16

# MODEL
structure: true
lj: true
coulomb: false

useBasis: true
useCharge: true
useTopoHelp: false

# OPTIMIZER
warmup_steps: 0.05
