# configable
epochs: 10
ckpt: ./ckpt/spbnet.160k.ckpt

# test
root_dir: ./test/demo/data/toydataset
id_prop: benchmark.filter
task: CO2-298-2.5
task_type: regression
log_dir: ./test/demo/logs
device: [0]

# stable
batch_size: 8
accelerator: gpu
strategy: ddp_find_unused_parameters_true
accumulate_grad_batches: 4
precision: 16-mixed
log_every_n_steps: 10

# MODEL
structure: true
lj: true
coulomb: false

useBasis: true
useCharge: false
useGrad: false
useTopoHelp: false
