# configable
epochs: 60
ckpt: ./test/demo/logs/CO2-298-2.5/version_0/checkpoints/epoch=7-step=40.ckpt

# test
root_dir: ./test/demo/data/toydataset
modal_folder: "."
id_prop: benchmark.filter.test
log_dir: ./test/demo/predict
device: [0]

batch_size: 16
precision: 16-mixed

# MODEL
structure: true
lj: true
coulomb: false

useBasis: true
useCharge: false
useTopoHelp: false

# OPTIMIZER
warmup_steps: 0.05
